//
//  InfoSheetView.swift
//  WeatherMood
//

import SwiftUI

struct InfoSheetView: View {
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 28) {

                    // Feels-like temp
                    InfoSection(
                        emoji: "🌡️",
                        title: "How \"feels like\" is calculated",
                        content: "The temperature shown isn't the air temperature — it's the **apparent temperature**: how warm or cold it actually feels on your skin.\n\nIt's calculated by combining the actual air temperature with **wind chill** (wind makes cold air feel colder) and the **heat index** (humidity makes warm air feel hotter). The number shown is the median apparent temperature between 8 AM and 8 PM, so it reflects the bulk of your waking day — not the overnight low dragging it down."
                    )

                    Divider()

                    // L / H
                    InfoSection(
                        emoji: "↕️",
                        title: "High & Low",
                        content: "The **H:** and **L:** values are the highest and lowest apparent temperatures across the full 24-hour day — so you know the real extremes, not just the daytime feel."
                    )

                    Divider()

                    // Recommendations
                    InfoSection(
                        emoji: "🧥",
                        title: "How dressing advice works",
                        content: "Recommendations are generated by a simple rule engine:\n\n• **Feels like < 10°C** → warm jacket\n• **Feels like 10–16°C** → light layer\n• **Gusts > 30 km/h** → wind layer\n• **Gusts > 50 km/h** → very gusty warning\n• **Rain likely (> 50% any hour)** → umbrella, with the specific time window\n• **UV index > 4** → sunscreen\n• **UV index > 7** → sunscreen + hat\n• **Humidity > 80% and warm** → muggy warning\n\nYesterday's card shows the same logic in past tense so you can see how accurate the advice would have been."
                    )

                    Divider()

                    // Data source
                    InfoSection(
                        emoji: "📡",
                        title: "Where the data comes from",
                        content: "Weather data is fetched from **Open-Meteo** (open-meteo.com) — a free, open-source weather API with no API key required. It uses high-resolution European weather models and is updated hourly."
                    )

                    Spacer(minLength: 20)
                }
                .padding(24)
            }
            .navigationTitle("How it works")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                        .fontWeight(.semibold)
                }
            }
        }
    }
}

// MARK: - Section component

private struct InfoSection: View {
    let emoji: String
    let title: String
    let content: String

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(spacing: 8) {
                Text(emoji)
                    .font(.title3)
                Text(title)
                    .font(.headline)
            }
            Text(.init(content))   // .init parses **markdown** bold
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .lineSpacing(3)
        }
    }
}
